# Generated by Django 3.2.8 on 2021-10-24 12:52

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=255)),
                ('productImage', models.ImageField(upload_to=apps.products.models.nameFile)),
            ],
        ),
    ]
